<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.10.0" xml:lang="en-US">
  <compounddef id="classgame_1_1utils_1_1exceptions_1_1PlayerNameAlreadyExists" kind="class" language="Python" prot="public">
    <compoundname>game::utils::exceptions::PlayerNameAlreadyExists</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
    <sectiondef kind="public-func">
      <memberdef kind="function" id="classgame_1_1utils_1_1exceptions_1_1PlayerNameAlreadyExists_1a33383c76fb3a7f4d2923e110d8d43ae8" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type></type>
        <definition>game.utils.exceptions.PlayerNameAlreadyExists.__init__</definition>
        <argsstring>(self, message=&quot;Your current player name is already taken, please change it.&quot;)</argsstring>
        <name>__init__</name>
        <qualifiedname>game.utils.exceptions.PlayerNameAlreadyExists.__init__</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>message</type>
          <defname>message</defname>
          <defval>&quot;Your current player name is already taken, please change it.&quot;</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" line="54" column="1" bodyfile="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" bodystart="54" bodyend="57"/>
      </memberdef>
    </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para><verbatim>Class for creating the exception caused by joining a server with an in-game name that is already taken.
</verbatim> </para>
    </detaileddescription>
    <inheritancegraph>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="1">
        <label>game.utils.exceptions.PlayerNameAlreadyExists</label>
        <link refid="classgame_1_1utils_1_1exceptions_1_1PlayerNameAlreadyExists"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="1">
        <label>game.utils.exceptions.PlayerNameAlreadyExists</label>
        <link refid="classgame_1_1utils_1_1exceptions_1_1PlayerNameAlreadyExists"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" line="49" column="1" bodyfile="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" bodystart="49" bodyend="57"/>
    <listofallmembers>
      <member refid="classgame_1_1utils_1_1exceptions_1_1PlayerNameAlreadyExists_1a33383c76fb3a7f4d2923e110d8d43ae8" prot="public" virt="non-virtual"><scope>game::utils::exceptions::PlayerNameAlreadyExists</scope><name>__init__</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
