<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.10.0" xml:lang="en-US">
  <compounddef id="classgame_1_1utils_1_1exceptions_1_1OutOfMapBounds" kind="class" language="Python" prot="public">
    <compoundname>game::utils::exceptions::OutOfMapBounds</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
    <sectiondef kind="public-func">
      <memberdef kind="function" id="classgame_1_1utils_1_1exceptions_1_1OutOfMapBounds_1a3c6ca7c3cace8096cf29033eda46d3b1" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>None</type>
        <definition> None game.utils.exceptions.OutOfMapBounds.__init__</definition>
        <argsstring>(self, message=&quot;Out of map boundaries, make sure to stay within them!&quot;)</argsstring>
        <name>__init__</name>
        <qualifiedname>game.utils.exceptions.OutOfMapBounds.__init__</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>message</type>
          <defname>message</defname>
          <defval>&quot;Out of map boundaries, make sure to stay within them!&quot;</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" line="26" column="1" bodyfile="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" bodystart="26" bodyend="29"/>
      </memberdef>
    </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para><verbatim>Class for creating the exception caused by overflowing the map data array.
</verbatim> </para>
    </detaileddescription>
    <inheritancegraph>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="1">
        <label>game.utils.exceptions.OutOfMapBounds</label>
        <link refid="classgame_1_1utils_1_1exceptions_1_1OutOfMapBounds"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="1">
        <label>game.utils.exceptions.OutOfMapBounds</label>
        <link refid="classgame_1_1utils_1_1exceptions_1_1OutOfMapBounds"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" line="21" column="1" bodyfile="/home/samuel/Documents/Python/Tile-Game/game/utils/exceptions.py" bodystart="21" bodyend="29"/>
    <listofallmembers>
      <member refid="classgame_1_1utils_1_1exceptions_1_1OutOfMapBounds_1a3c6ca7c3cace8096cf29033eda46d3b1" prot="public" virt="non-virtual"><scope>game::utils::exceptions::OutOfMapBounds</scope><name>__init__</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
